### ISSUE TITLE
安装后无法使用

### ISSUE THREAD

**Issue by bestony** [jsthon/flarum-simplified-chinese#7]
单独开始simplified-chinese会出现core.forum.discussion_list.empty_text 这样的字样。
开启English 会显示英文。
版本v0.1.0-beta.4

**Comment by bestony** [comment]
已解决，需要前台切换。后台不自动切换。

**Comment by Winlang** [comment]
嗨 你好 这个问题你是怎么解决的呢？怎么切换？
